// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlY8pGt7DfWBzBcwH6iOoBz3tGdWr-Rnk',
    appId: '1:154293243629:web:f2b39976c28fd7121586e4',
    messagingSenderId: '154293243629',
    projectId: 'wndr-c2591',
    authDomain: 'wndr-c2591.firebaseapp.com',
    storageBucket: 'wndr-c2591.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW9fuYi0N-J6n3by5YvdXeYo_uMro3-xg',
    appId: '1:154293243629:android:ea78f3a6fe7375a31586e4',
    messagingSenderId: '154293243629',
    projectId: 'wndr-c2591',
    storageBucket: 'wndr-c2591.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVSqeBujhGgvx41nB6Hq5ZP3EjxLcIYPI',
    appId: '1:154293243629:ios:85152eefe97752e21586e4',
    messagingSenderId: '154293243629',
    projectId: 'wndr-c2591',
    storageBucket: 'wndr-c2591.appspot.com',
    iosClientId: '154293243629-2ir8dffcl3h261pmkireh8tkp1nq2srg.apps.googleusercontent.com',
    iosBundleId: 'com.example.wndr',
  );
}
